/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cQVDyyhp1eFbJfKFr4wFDe

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantszf3L9NpB2LCp } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zf3L9NpB2LCp/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantszf3L9NpB2LCp
});
